FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    texlive-xetex texlive-luatex texlive-latex-recommended \
    texlive-latex-extra texlive-lang-japanese texlive-fonts-extra \
    libcairo2