table-of-contents: true
toc-depth: 2
number-sections: true
wrap: preserve

pdf-engine: lualatex
pdf-engine-opts:
  - "-interaction=nonstopmode"
  - "-halt-on-error"
  - "-shell-escape"

metadata:
  toc-title: 目次
  reference-section-title: 参考文献
  link-citations: true

variables:
  colorlinks: true
  toccolor: Maroon
  linkcolor: RedViolet
  filecolor: RedViolet
  citecolor: NavyBlue
  urlcolor: NavyBlue
  indent: true
  documentclass: jlreq
  fontsize: 10.5pt
  papersize: a4
  classoption:
    - jafontscale=0.92
    - hanging_punctuation
    - head_space=24.8mm
    - foot_space=24.8mm
  # mainfont: Libertinus Serif
  # mainfontoptions:
  #   - UprightFont=*-Regular
  #   - ItalicFont=*-Italic
  #   - BoldFont=*-Semibold
  #   - BoldItalicFont=*-SemiboldItalic
  # sansfont: Libertinus Sans
  # sansfontoptions:
  #   - UprightFont=*-Regular
  #   - ItalicFont=*-Italic
  #   - BoldFont=*-Bold
  #   - BoldItalicFont=*-Bold
  #   - Scale=1.08
  # mathfont: Libertinus Math
  mainfont: TeX Gyre Pagella
  mathfont: TeX Gyre Pagella Math
  sansfont: Fira Sans
  sansfontoptions:
    - Scale=1.00
  monofont: Fira Code
  monofontoptions:
    - Scale=0.85
  luatexjapresetoptions:
    - deluxe
    - match
    - nfssonly
    - jis2004
  _luatexjapreset:
    - mc-l=HaranoAjiMincho-Light  # 明朝体細字 \mcfamily\ltseries
    - mc-m=HaranoAjiMincho-Regular  # 明朝体中字 \mcfamily\mdseries
    - mc-b=HaranoAjiMincho-Bold  # 明朝体太字 \mcfamily\bfseries
    - gt-m=HaranoAjiGothic-Regular  # ゴシック体中字 \gtfamily\mdseries
    - gt-b=HaranoAjiGothic-Bold  # ゴシック体太字 \gtfamily\bfseries
    - gt-eb=HaranoAjiGothic-Heavy # ゴシック体極太字 \gtfamily\ebseries
  _sectionfont: \Large\sffamily\gtfamily\mdseries
  _sectionoption: lines=2.3,before_lines=0,after_lines=0
  _subsectionfont: \large\sffamily\gtfamily\mdseries
  _subsectionoption: lines=1.8,before_lines=0,after_lines=0
  _subsubsectionfont: \normalsize\sffamily\gtfamily\mdseries
  _subsubsectionoption: lines=1.3,before_lines=0,after_lines=0
  _paragraphfont: \normalsize\sffamily\gtfamily\mdseries
  _subparagraphfont: \normalsize\sffamily\gtfamily\mdseries
