name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} and Pandoc ${{ matrix.pandoc-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        pandoc-version: ['3.0.1', '3.1', '3.1.12', 'latest']

    steps:
      - uses: actions/checkout@v4
      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install texlive-xetex texlive-luatex texlive-latex-recommended
          sudo apt-get install texlive-latex-extra texlive-lang-japanese
          sudo apt-get install libcairo2
          lualatex --version
      - name: Install Pandoc
        run: |
          [[ ${{ matrix.pandoc-version }} == "latest" ]] && url="https://github.com/jgm/pandoc/releases/latest" || url="https://github.com/jgm/pandoc/releases/tag/${{ matrix.pandoc-version }}"
          url=$(curl -L $url | grep -o 'https://[a-zA-Z/.]*expanded_assets/[0-9.]*')
          downloadUrl="https://github.com$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')"
          wget --no-verbose "$downloadUrl"
          sudo dpkg -i "${downloadUrl##*/}"
          pandoc --version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: pip install --upgrade hatch
      - name: Check format
        run: hatch fmt --check
      - name: Install Packages
        run : |
          pip install --upgrade aiohttp nbformat panflute pyyaml rich typer
          pip install --upgrade pytest-cov matplotlib cairosvg
          pip install -e .
      - name: Run test
        run: pytest
      - name: Upload Codecov Results
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info